services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $locales: '%kernel.enabled_locales%'
            $fromAddress: '%sfs_mailer.from_email.address%'
            $fromName: '%sfs_mailer.from_email.sender_name%'

    Softspring\MailerBundle\EventListener\EmailFromListener: ~