services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Softspring\MailerBundle\EventListener\MessageSendingEventListener:
        arguments:
            $em: '@doctrine.orm.entity_manager'
        tags: ['kernel.event_subscriber']

    Softspring\MailerBundle\EventListener\MessageFailedEventListener:
        arguments:
            $em: '@doctrine.orm.entity_manager'
            $removeFailed: '%sfs_mailer.spool.remove_failed%'
        tags: ['kernel.event_subscriber']

    Softspring\MailerBundle\EventListener\MessageSentEventListener:
        arguments:
            $em: '@doctrine.orm.entity_manager'
            $removeSent: '%sfs_mailer.spool.remove_sent%'
        tags: ['kernel.event_subscriber']

    Softspring\MailerBundle\Spool\DatabaseSpool:
        arguments:
            $em: '@doctrine.orm.entity_manager'
            $class: '%sfs_mailer.spool.class%'
            $dispatcher: '@event_dispatcher'

    Softspring\MailerBundle\Spool\SpoolManager: ~

    swiftmailer.spool.sfs_mailer_db:
        alias: 'Softspring\MailerBundle\Spool\DatabaseSpool'

    swiftmailer.mailer.default.spool.sfs_mailer_db:
        alias: 'Softspring\MailerBundle\Spool\DatabaseSpool'
