services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $locales: '%sfs_core.locales%'
            $fromAddress: '%sfs_mailer.from_email.address%'
            $fromName: '%sfs_mailer.from_email.sender_name%'

    Softspring\MailerBundle\Mime\TranslatableBodyRenderer:
        decorates: twig.mime_body_renderer
        arguments: ['@Softspring\MailerBundle\Mime\TranslatableBodyRenderer.inner', '@translator.default']

    Softspring\MailerBundle\EventListener\EmailFromListener: ~

    Softspring\MailerBundle\Controller\Admin\MailerTemplateController:
        public: true
        tags: ['controller.service_arguments']
#
    Softspring\MailerBundle\Controller\Admin\MailerHistoryController:
        public: true
        tags: ['controller.service_arguments']
#
    Softspring\MailerBundle\Template\TemplateLoader:
        arguments:
            $templateLoaders: null

    Softspring\MailerBundle\Template\Loader\ParameterTemplateLoader:
        arguments:
            $templatesConfig: '%sfs_mailer.templates%'
        tags: ['sfs_mailer.template_loader']

    Softspring\MailerBundle\Command\ListTemplatesCommand:
        tags: ['console.command']

#    Softspring\MailerBundle\Command\SendTemplateCommand:
#        arguments:
#            $templateMailer: '@Softspring\MailerBundle\Mailer\TemplateMailer'
#        tags: ['console.command']