sfs_mailer_templates_search:
    defaults:
        _controller: Softspring\MailerBundle\Controller\Admin\MailerTemplateController::search
    path: /

sfs_mailer_templates_test:
    defaults:
        _controller: Softspring\MailerBundle\Controller\Admin\MailerTemplateController::test
    path: /{template}/test

sfs_mailer_templates_preview:
    defaults:
        _controller: Softspring\MailerBundle\Controller\Admin\MailerTemplateController::preview
    path: /{template}/preview

