sfs_mailer_templates_search:
    defaults:
        _controller: Softspring\MailerBundle\Controller\MailerTemplateController::search
    path: /

sfs_mailer_templates_test:
    defaults:
        _controller: Softspring\MailerBundle\Controller\MailerTemplateController::test
    path: /{templateId}

